services:
  - type: web
    name: servicio-social
    runtime: php
    region: oregon
    plan: free
    branch: main
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      npm install
      npm run build
      php artisan config:cache
    startCommand: php -S 0.0.0.0:$PORT -t public
    autoDeploy: true
    envVars:
      - key: APP_NAME
        value: "Servicio Social"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        sync: false
      - key: APP_KEY
        sync: false

      - key: DB_CONNECTION
        value: "pgsql"
      - key: DB_HOST
        fromDatabase:
          name: servicio-social-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: servicio-social-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: servicio-social-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: servicio-social-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: servicio-social-db
          property: password

databases:
  - name: servicio-social-db
    plan: free
    region: oregon
